### ISSUE TITLE
Provide the version of a module at runtime.

### ISSUE THREAD

**Issue by seb-pereira** [ibm-js/sdk#7]
It can be useful to know what release if actually used at runtime. In D1 we have `dojo.version`. However it doesn't allow to get other modules version (dijit/dojox...). 

This could be valuable to have this information:
- for support, in order to display the version number of modules actually used in samples test cases. 
- It could be used for an application that  wants generate a report (support) or an "about" dialog with detailed information.

Not sure how we could provide this but it should be consistent across modules. 

Any thoughts?

**Comment by cjolif** [comment]
by module,  I guess you meant "project" or "package"? I don't think we want this per AMD module?

**Comment by seb-pereira** [comment]
Yes, I mean project/package: delite/deliteful...

**Comment by cjolif** [comment]
isn't the version in bower.json & package.json enough?

**Comment by seb-pereira** [comment]
The idea would be to have something like this:

``` js
define([
    "deliteful/meta"
], function (deliteful) {
   deliteful.version();
});
```

This can be refined but this is the spirit. 
For sure we have the information in bower.json and package.json; I wonder how we could automate the creation of a "meta.js" or whatever its name, that will contain information such as the version or other informations (why not dependencies, licenses url from package.json...). I guess it would be something to do as part of a build  process.

**Comment by wkeese** [comment]
It sounds like a good idea, not sure how to do it either but something like the code you have above seems reasonable.   Maybe a file called version.js?

**Comment by seb-pereira** [comment]
Yes, a file called `version.js` could provide the meta info.
On second thought, it might be easiest just to consume `package.json` to get meta information at runtime. A user still can add custom information in this file.

CC @clmath. Should each project manage its own `version.js` module to load and expose information from `package.js`, or is it possible to have a cross-project way to do that with a requirejs plugin for example?

**Comment by AdrianVasiliu** [comment]
Consumming `package.json` at runtime wouldn't work for an app using a custom built version of the project not including this file... Rather than enforcing the inclusion in the build, it would seem we'd better generate the `version.js` "statically".

**Comment by seb-pereira** [comment]
So, a static `version.js` would be committed before and after a git tag which leads to a shell script or a grunt task workflow like this one:
1. generate and commit `version.js` which contains the target version.
2. tag the branch with the target version
3. generate and commit `version.js` which indicates this is a version in progress.

**Comment by wkeese** [comment]
Makes sense, and sounds a lot like dojo's util/buildscripts/build_release.sh.

**Comment by cjolif** [comment]
> Rather than enforcing the inclusion in the build, it would seem we'd better generate the version.js "statically".

How is that different to enforce the inclusion of package.json (or I would say bower.json in our case) vs the inclusion of versions.js? To me it sounds very similar. In both case you will have to force inclusion in the build if you want to see them in?

> So, a static version.js would be committed before and after a git tag which leads to a shell script or a grunt task workflow like this one

Ok. But the version is also in bower.json and we must make sure to not diverge here. So either we also generate bower.json in a similar manner or we extract version.js from bower.json (or we just keep bower.json and provide an easy runtime way to read the version field in there)
